
import { Food, generateId } from "../../types";

export const ALCOHOLIC_BEVERAGES: Food[] = [
  {
    id: generateId("alc", 1),
    name: "Beer, regular",
    serving: "12 oz (355 ml)",
    calories: 153,
    protein: 1.7,
    carbs: 12.8,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 14,
    calcium: 14,
    iron: 0.01,
    vitaminC: 0,
    category: "alcohol",
  },
  {
    id: generateId("alc", 2),
    name: "Beer, light",
    serving: "12 oz (355 ml)",
    calories: 104,
    protein: 0.9,
    carbs: 5.8,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 10,
    calcium: 7,
    iron: 0,
    vitaminC: 0,
    category: "alcohol",
  },
  {
    id: generateId("alc", 3),
    name: "Red wine",
    serving: "5 oz (148 ml)",
    calories: 125,
    protein: 0.1,
    carbs: 4,
    fiber: 0,
    sugars: 0.9,
    fat: 0,
    sodium: 5,
    calcium: 12,
    iron: 0.5,
    vitaminC: 0,
    category: "alcohol",
  },
  {
    id: generateId("alc", 4),
    name: "White wine",
    serving: "5 oz (148 ml)",
    calories: 121,
    protein: 0.1,
    carbs: 3.8,
    fiber: 0,
    sugars: 1.4,
    fat: 0,
    sodium: 7,
    calcium: 9,
    iron: 0.3,
    vitaminC: 0,
    category: "alcohol",
  },
  {
    id: generateId("alc", 5),
    name: "Whiskey (40% ABV)",
    serving: "1.5 oz (44 ml)",
    calories: 97,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 0,
    calcium: 0,
    iron: 0,
    vitaminC: 0,
    category: "alcohol",
  },
];

export default ALCOHOLIC_BEVERAGES;

