
import { Food, generateId } from "../types";

export const BEVERAGES: Food[] = [
  {
    id: generateId("bev", 1),
    name: "Water, plain",
    serving: "1 cup (240 ml)",
    calories: 0,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 0,
    calcium: 0,
    iron: 0,
    vitC: 0,
    category: "beverage",
  },
  {
    id: generateId("bev", 2),
    name: "Coffee, black",
    serving: "1 cup (240 ml)",
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 5,
    calcium: 5,
    iron: 0,
    vitC: 0,
    category: "beverage",
  },
  {
    id: generateId("bev", 3),
    name: "Tea, black",
    serving: "1 cup (240 ml)",
    calories: 2,
    protein: 0,
    carbs: 0.5,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 7,
    calcium: 0,
    iron: 0,
    vitC: 0,
    category: "beverage",
  },
  {
    id: generateId("bev", 4),
    name: "Soda (Cola, reg.)",
    serving: "12 oz can (355 ml)",
    calories: 140,
    protein: 0,
    carbs: 39,
    fiber: 0,
    sugars: 39,
    fat: 0,
    sodium: 45,
    calcium: 2,
    iron: 0,
    vitC: 0,
    category: "beverage",
  },
  {
    id: generateId("bev", 5),
    name: "Diet Cola (no sugar)",
    serving: "12 oz can (355 ml)",
    calories: 1,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 40,
    calcium: 0,
    iron: 0,
    vitC: 0,
    category: "beverage",
  },
  {
    id: generateId("bev", 6),
    name: "Orange juice",
    serving: "8 oz glass (240 ml)",
    calories: 112,
    protein: 1.7,
    carbs: 26,
    fiber: 0.5,
    sugars: 21,
    fat: 0.3,
    sodium: 2,
    calcium: 20,
    iron: 0.5,
    vitC: 124,
    category: "beverage",
  },
  {
    id: generateId("bev", 7),
    name: "Apple juice",
    serving: "8 oz glass (240 ml)",
    calories: 113,
    protein: 0.1,
    carbs: 28,
    fiber: 0.2,
    sugars: 24,
    fat: 0.3,
    sodium: 7,
    calcium: 20,
    iron: 0.2,
    vitC: 0,
    category: "beverage",
  },
];

export default BEVERAGES;

