
import { Food, generateId } from "../../types";

export const FRUITS: Food[] = [
  {
    id: generateId("frt", 1),
    name: "Apple (with skin)",
    serving: "1 medium (182 g)",
    calories: 95,
    protein: 0.5,
    carbs: 25.1,
    fiber: 4.4,
    sugars: 18.9,
    fat: 0.3,
    sodium: 2,
    calcium: 11,
    iron: 0.2,
    vitaminC: 8.4,
    category: "fruit",
  },
  {
    id: generateId("frt", 2),
    name: "Banana",
    serving: "1 medium (118 g)",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fiber: 3.1,
    sugars: 14.4,
    fat: 0.4,
    sodium: 1,
    calcium: 6,
    iron: 0.3,
    vitaminC: 10,
    category: "fruit",
  },
  {
    id: generateId("frt", 3),
    name: "Orange",
    serving: "1 medium (154 g)",
    calories: 72,
    protein: 1.4,
    carbs: 18.1,
    fiber: 3.7,
    sugars: 14.5,
    fat: 0.2,
    sodium: 0,
    calcium: 62,
    iron: 0.1,
    vitaminC: 77,
    category: "fruit",
  },
  {
    id: generateId("frt", 4),
    name: "Grapes",
    serving: "1 cup (92 g)",
    calories: 62,
    protein: 0.6,
    carbs: 16,
    fiber: 0.8,
    sugars: 15,
    fat: 0.3,
    sodium: 2,
    calcium: 15,
    iron: 0.3,
    vitaminC: 4,
    category: "fruit",
  },
  {
    id: generateId("frt", 5),
    name: "Strawberries",
    serving: "1 cup, halves (152 g)",
    calories: 49,
    protein: 1,
    carbs: 12,
    fiber: 3,
    sugars: 7,
    fat: 0.3,
    sodium: 1,
    calcium: 23,
    iron: 0.4,
    vitaminC: 89,
    category: "fruit",
  },
  {
    id: generateId("frt", 6),
    name: "Blueberries",
    serving: "1 cup (148 g)",
    calories: 84,
    protein: 1.1,
    carbs: 21,
    fiber: 3.6,
    sugars: 15,
    fat: 0.5,
    sodium: 1,
    calcium: 9,
    iron: 0.4,
    vitaminC: 14,
    category: "fruit",
  },
  {
    id: generateId("frt", 7),
    name: "Peach",
    serving: "1 medium (150 g)",
    calories: 59,
    protein: 1.4,
    carbs: 15,
    fiber: 2.3,
    sugars: 13,
    fat: 0.4,
    sodium: 0,
    calcium: 9,
    iron: 0.3,
    vitaminC: 10,
    category: "fruit",
  },
  {
    id: generateId("frt", 8),
    name: "Pineapple",
    serving: "1 cup, chunks (165 g)",
    calories: 83,
    protein: 0.9,
    carbs: 22,
    fiber: 2.3,
    sugars: 16,
    fat: 0.2,
    sodium: 2,
    calcium: 20,
    iron: 0.4,
    vitaminC: 79,
    category: "fruit",
  },
];

export default FRUITS;

