
import { Food, generateId } from "../types";

export const PROTEIN_FOODS: Food[] = [
  {
    id: generateId("protein", 1),
    name: "Chicken breast (roasted)",
    serving: "1/2 breast (86 g)",
    calories: 142,
    protein: 26.7,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 3.1,
    sodium: 64,
    calcium: 5,
    iron: 0.5,
    vitC: 0,
    category: "protein",
  },
  {
    id: generateId("protein", 2),
    name: "Beef, ground (80% lean)",
    serving: "1 patty (113 g)",
    calories: 288,
    protein: 30,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 19.8,
    sodium: 85,
    calcium: 6,
    iron: 2.9,
    vitC: 0,
    category: "protein",
  },
  {
    id: generateId("protein", 3),
    name: "Egg, whole (boiled)",
    serving: "1 large (50 g)",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fiber: 0,
    sugars: 0.6,
    fat: 5.3,
    sodium: 62,
    calcium: 25,
    iron: 0.6,
    vitC: 0,
    category: "protein",
  },
  {
    id: generateId("protein", 4),
    name: "Tofu, firm",
    serving: "~1/2 cup (100 g)",
    calories: 76,
    protein: 8.1,
    carbs: 1.9,
    fiber: 0.3,
    sugars: 0.7,
    fat: 4.8,
    sodium: 7,
    calcium: 350,
    iron: 5.4,
    vitC: 0,
    category: "protein",
  },
  {
    id: generateId("nut", 5),
    name: "Almonds",
    serving: "1 oz (28 g)",
    calories: 162,
    protein: 6,
    carbs: 6.2,
    fiber: 3.5,
    sugars: 1.2,
    fat: 14,
    sodium: 1,
    calcium: 75,
    iron: 1,
    vitC: 0,
    category: "nut",
  },
];

export default PROTEIN_FOODS;
