
import { Food, generateId } from "../types";

export const VEGETABLES: Food[] = [
  {
    id: generateId("veg", 1),
    name: "Tomato, raw",
    serving: "1 medium (123 g)",
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fiber: 1.5,
    sugars: 3.2,
    fat: 0.3,
    sodium: 6,
    calcium: 12,
    iron: 0.4,
    vitC: 17,
    category: "vegetable",
  },
  {
    id: generateId("veg", 2),
    name: "Potato, baked",
    serving: "1 med. w/ skin (173 g)",
    calories: 161,
    protein: 4.3,
    carbs: 36,
    fiber: 3.8,
    sugars: 2.2,
    fat: 0.2,
    sodium: 17,
    calcium: 17,
    iron: 1.2,
    vitC: 22,
    category: "vegetable",
  },
  {
    id: generateId("veg", 3),
    name: "Broccoli, cooked",
    serving: "~2 spears (150 g)",
    calories: 53,
    protein: 3.6,
    carbs: 10.8,
    fiber: 5.0,
    sugars: 2.1,
    fat: 0.6,
    sodium: 62,
    calcium: 60,
    iron: 1.1,
    vitC: 97,
    category: "vegetable",
  },
  {
    id: generateId("veg", 4),
    name: "Carrot, raw",
    serving: "1 medium (61 g)",
    calories: 25,
    protein: 0.5,
    carbs: 6.1,
    fiber: 1.7,
    sugars: 2.9,
    fat: 0.1,
    sodium: 18,
    calcium: 20,
    iron: 0.2,
    vitC: 4,
    category: "vegetable",
  },
  {
    id: generateId("veg", 5),
    name: "Lettuce (iceberg)",
    serving: "1 cup shredded (72 g)",
    calories: 10,
    protein: 0.6,
    carbs: 2.2,
    fiber: 0.9,
    sugars: 1.3,
    fat: 0.1,
    sodium: 7,
    calcium: 13,
    iron: 0.3,
    vitC: 2,
    category: "vegetable",
  },
  {
    id: generateId("veg", 6),
    name: "Bell pepper",
    serving: "1 medium (119 g)",
    calories: 37,
    protein: 1.2,
    carbs: 7.1,
    fiber: 2.5,
    sugars: 5,
    fat: 0.4,
    sodium: 2,
    calcium: 12,
    iron: 0.4,
    vitC: 100,
    category: "vegetable",
  },
  {
    id: generateId("veg", 7),
    name: "Cucumber, raw",
    serving: "½ large (150 g)",
    calories: 22,
    protein: 1,
    carbs: 5.4,
    fiber: 0.8,
    sugars: 2.6,
    fat: 0.1,
    sodium: 3,
    calcium: 16,
    iron: 0.3,
    vitC: 4,
    category: "vegetable",
  },
  {
    id: generateId("veg", 8),
    name: "Onion, raw",
    serving: "1 medium (110 g)",
    calories: 44,
    protein: 1.2,
    carbs: 10.2,
    fiber: 1.9,
    sugars: 4.6,
    fat: 0.1,
    sodium: 4,
    calcium: 25,
    iron: 0.2,
    vitC: 8,
    category: "vegetable",
  },
  {
    id: generateId("veg", 9),
    name: "Spinach, raw",
    serving: "1 cup (30 g)",
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fiber: 0.7,
    sugars: 0.1,
    fat: 0.1,
    sodium: 24,
    calcium: 30,
    iron: 0.8,
    vitC: 8,
    category: "vegetable",
  },
];

export default VEGETABLES;
