export interface FoodFull {
  id: string;
  name: string;
  serving: string;
  calories: number;
  protein: number;
  carbs: number;
  fiber: number;
  sugars: number;
  fat: number;
  sodium: number;
  calcium: number;
  iron: number;
  vitC: number;
}

// This is now the comprehensive full list. (If editing, consider breaking up into multiple files for maintainability.)
export const FULL_FOOD_DATABASE: FoodFull[] = [
  // --- Beverages (Non-Alcoholic) ---
  {
    id: "1",
    name: "Water, plain",
    serving: "1 cup (240 ml)",
    calories: 0,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 0,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  {
    id: "2",
    name: "Coffee, black",
    serving: "1 cup (240 ml)",
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 5,
    calcium: 5,
    iron: 0,
    vitC: 0,
  },
  {
    id: "3",
    name: "Tea, black",
    serving: "1 cup (240 ml)",
    calories: 2,
    protein: 0,
    carbs: 0.5,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 7,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  {
    id: "4",
    name: "Soda (Cola, reg.)",
    serving: "12 oz can (355 ml)",
    calories: 140,
    protein: 0,
    carbs: 39,
    fiber: 0,
    sugars: 39,
    fat: 0,
    sodium: 45,
    calcium: 2,
    iron: 0,
    vitC: 0,
  },
  {
    id: "5",
    name: "Diet Cola (no sugar)",
    serving: "12 oz can (355 ml)",
    calories: 1,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 40,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  {
    id: "6",
    name: "Orange juice",
    serving: "8 oz glass (240 ml)",
    calories: 112,
    protein: 1.7,
    carbs: 26,
    fiber: 0.5,
    sugars: 21,
    fat: 0.3,
    sodium: 2,
    calcium: 20,
    iron: 0.5,
    vitC: 124,
  },
  {
    id: "7",
    name: "Apple juice",
    serving: "8 oz glass (240 ml)",
    calories: 113,
    protein: 0.1,
    carbs: 28,
    fiber: 0.2,
    sugars: 24,
    fat: 0.3,
    sodium: 7,
    calcium: 20,
    iron: 0.2,
    vitC: 0,
  },
  // --- Alcoholic Beverages ---
  {
    id: "8",
    name: "Beer, regular",
    serving: "12 oz (355 ml)",
    calories: 153,
    protein: 1.7,
    carbs: 12.8,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 14,
    calcium: 14,
    iron: 0.01,
    vitC: 0,
  },
  {
    id: "9",
    name: "Beer, light",
    serving: "12 oz (355 ml)",
    calories: 104,
    protein: 0.9,
    carbs: 5.8,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 10,
    calcium: 7,
    iron: 0,
    vitC: 0,
  },
  {
    id: "10",
    name: "Red wine",
    serving: "5 oz (148 ml)",
    calories: 125,
    protein: 0.1,
    carbs: 4,
    fiber: 0,
    sugars: 0.9,
    fat: 0,
    sodium: 5,
    calcium: 12,
    iron: 0.5,
    vitC: 0,
  },
  {
    id: "11",
    name: "White wine",
    serving: "5 oz (148 ml)",
    calories: 121,
    protein: 0.1,
    carbs: 3.8,
    fiber: 0,
    sugars: 1.4,
    fat: 0,
    sodium: 7,
    calcium: 9,
    iron: 0.3,
    vitC: 0,
  },
  {
    id: "12",
    name: "Whiskey (40% ABV)",
    serving: "1.5 oz (44 ml)",
    calories: 97,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 0,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  // --- Fruits ---
  {
    id: "13",
    name: "Apple (with skin)",
    serving: "1 medium (182 g)",
    calories: 95,
    protein: 0.5,
    carbs: 25.1,
    fiber: 4.4,
    sugars: 18.9,
    fat: 0.3,
    sodium: 2,
    calcium: 11,
    iron: 0.2,
    vitC: 8.4,
  },
  {
    id: "14",
    name: "Banana",
    serving: "1 medium (118 g)",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fiber: 3.1,
    sugars: 14.4,
    fat: 0.4,
    sodium: 1,
    calcium: 6,
    iron: 0.3,
    vitC: 10,
  },
  {
    id: "15",
    name: "Orange",
    serving: "1 medium (154 g)",
    calories: 72,
    protein: 1.4,
    carbs: 18.1,
    fiber: 3.7,
    sugars: 14.5,
    fat: 0.2,
    sodium: 0,
    calcium: 62,
    iron: 0.1,
    vitC: 77,
  },
  {
    id: "16",
    name: "Grapes (seedless)",
    serving: "~20 grapes (92 g)",
    calories: 64,
    protein: 0.6,
    carbs: 16.6,
    fiber: 0.8,
    sugars: 14.0,
    fat: 0.2,
    sodium: 2,
    calcium: 10,
    iron: 0.2,
    vitC: 3,
  },
  {
    id: "17",
    name: "Strawberries",
    serving: "1 cup (152 g)",
    calories: 50,
    protein: 1.0,
    carbs: 11.7,
    fiber: 3.0,
    sugars: 7.4,
    fat: 0.5,
    sodium: 2,
    calcium: 24,
    iron: 0.4,
    vitC: 89,
  },
  {
    id: "18",
    name: "Watermelon",
    serving: "1 large wedge (280 g)",
    calories: 84,
    protein: 1.7,
    carbs: 21.3,
    fiber: 1.1,
    sugars: 17.4,
    fat: 0.6,
    sodium: 3,
    calcium: 20,
    iron: 0.6,
    vitC: 23,
  },
  {
    id: "19",
    name: "Peach",
    serving: "1 medium (150 g)",
    calories: 59,
    protein: 1.4,
    carbs: 15.0,
    fiber: 2.3,
    sugars: 12.5,
    fat: 0.4,
    sodium: 0,
    calcium: 9,
    iron: 0.3,
    vitC: 10,
  },
  {
    id: "20",
    name: "Pear",
    serving: "1 medium (178 g)",
    calories: 101,
    protein: 0.7,
    carbs: 27.0,
    fiber: 5.5,
    sugars: 17.4,
    fat: 0.2,
    sodium: 2,
    calcium: 16,
    iron: 0.4,
    vitC: 7.6,
  },
  {
    id: "21",
    name: "Blueberries",
    serving: "1 cup (148 g)",
    calories: 84,
    protein: 1.1,
    carbs: 21.5,
    fiber: 3.6,
    sugars: 14.7,
    fat: 0.5,
    sodium: 1,
    calcium: 9,
    iron: 0.4,
    vitC: 14,
  },
  {
    id: "22",
    name: "Raspberries",
    serving: "1 cup (123 g)",
    calories: 64,
    protein: 1.5,
    carbs: 14.7,
    fiber: 8.0,
    sugars: 5.4,
    fat: 0.8,
    sodium: 1,
    calcium: 25,
    iron: 0.8,
    vitC: 32,
  },
  {
    id: "23",
    name: "Cherries",
    serving: "1 cup (154 g)",
    calories: 97,
    protein: 1.6,
    carbs: 25.0,
    fiber: 3.2,
    sugars: 19.7,
    fat: 0.3,
    sodium: 0,
    calcium: 19,
    iron: 0.5,
    vitC: 11,
  },
  {
    id: "24",
    name: "Pineapple",
    serving: "1 cup (165 g)",
    calories: 83,
    protein: 0.9,
    carbs: 21.6,
    fiber: 2.3,
    sugars: 16.3,
    fat: 0.2,
    sodium: 2,
    calcium: 22,
    iron: 0.4,
    vitC: 79,
  },
  {
    id: "25",
    name: "Mango",
    serving: "~½ fruit (100 g)",
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fiber: 1.6,
    sugars: 13.7,
    fat: 0.2,
    sodium: 1,
    calcium: 7,
    iron: 0.1,
    vitC: 36,
  },
  {
    id: "26",
    name: "Avocado",
    serving: "1 medium (150 g)",
    calories: 240,
    protein: 3.0,
    carbs: 12.0,
    fiber: 10.0,
    sugars: 0.7,
    fat: 22.0,
    sodium: 10,
    calcium: 18,
    iron: 1.0,
    vitC: 12,
  },
  {
    id: "27",
    name: "Kiwi",
    serving: "1 medium (76 g)",
    calories: 48,
    protein: 0.8,
    carbs: 11.0,
    fiber: 2.3,
    sugars: 7.9,
    fat: 0.3,
    sodium: 2,
    calcium: 23,
    iron: 0.2,
    vitC: 64,
  },
  {
    id: "28",
    name: "Cranberries",
    serving: "1 cup (100 g)",
    calories: 46,
    protein: 0.4,
    carbs: 12.2,
    fiber: 4.6,
    sugars: 8.0,
    fat: 0.1,
    sodium: 2,
    calcium: 8,
    iron: 0.3,
    vitC: 13,
  },
  {
    id: "29",
    name: "Lemon",
    serving: "1 medium (58 g)",
    calories: 17,
    protein: 0.6,
    carbs: 5.4,
    fiber: 1.5,
    sugars: 1.5,
    fat: 0.2,
    sodium: 1,
    calcium: 15,
    iron: 0.3,
    vitC: 30,
  },
  {
    id: "30",
    name: "Lime",
    serving: "1 medium (67 g)",
    calories: 20,
    protein: 0.5,
    carbs: 7.0,
    fiber: 1.9,
    sugars: 1.7,
    fat: 0.1,
    sodium: 1,
    calcium: 22,
    iron: 0.4,
    vitC: 29,
  },
  // --- Vegetables ---
  {
    id: "31",
    name: "Tomato, raw",
    serving: "1 medium (123 g)",
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fiber: 1.5,
    sugars: 3.2,
    fat: 0.3,
    sodium: 6,
    calcium: 12,
    iron: 0.4,
    vitC: 17,
  },
  {
    id: "32",
    name: "Potato, baked",
    serving: "1 med. w/ skin (173 g)",
    calories: 161,
    protein: 4.3,
    carbs: 36,
    fiber: 3.8,
    sugars: 2.2,
    fat: 0.2,
    sodium: 17,
    calcium: 17,
    iron: 1.2,
    vitC: 22,
  },
  {
    id: "33",
    name: "Sweet potato, baked",
    serving: "1 medium (114 g)",
    calories: 103,
    protein: 2.3,
    carbs: 24,
    fiber: 3.8,
    sugars: 7.4,
    fat: 0.2,
    sodium: 27,
    calcium: 18,
    iron: 0.5,
    vitC: 2,
  },
  {
    id: "34",
    name: "Carrots, raw",
    serving: "1 medium (61 g)",
    calories: 25,
    protein: 0.6,
    carbs: 5.8,
    fiber: 1.7,
    sugars: 2.9,
    fat: 0.1,
    sodium: 42,
    calcium: 20,
    iron: 0.2,
    vitC: 4,
  },
  {
    id: "35",
    name: "Broccoli, cooked",
    serving: "~2 spears (150 g)",
    calories: 53,
    protein: 3.6,
    carbs: 10.8,
    fiber: 5.0,
    sugars: 2.1,
    fat: 0.6,
    sodium: 62,
    calcium: 60,
    iron: 1.1,
    vitC: 97,
  },
  {
    id: "36",
    name: "Spinach, raw",
    serving: "1 cup (30 g)",
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fiber: 0.7,
    sugars: 0.1,
    fat: 0.1,
    sodium: 24,
    calcium: 30,
    iron: 0.8,
    vitC: 8,
  },
  {
    id: "37",
    name: "Lettuce (iceberg)",
    serving: "1 cup shredded (72 g)",
    calories: 10,
    protein: 0.6,
    carbs: 2.2,
    fiber: 0.9,
    sugars: 1.3,
    fat: 0.1,
    sodium: 7,
    calcium: 13,
    iron: 0.3,
    vitC: 2,
  },
  {
    id: "38",
    name: "Cucumber",
    serving: "~½ medium (104 g)",
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fiber: 1.5,
    sugars: 1.7,
    fat: 0.1,
    sodium: 2,
    calcium: 15,
    iron: 0.3,
    vitC: 3,
  },
  {
    id: "39",
    name: "Bell pepper, red",
    serving: "1 medium (119 g)",
    calories: 31,
    protein: 1.0,
    carbs: 7.3,
    fiber: 2.5,
    sugars: 4.8,
    fat: 0.3,
    sodium: 4,
    calcium: 11,
    iron: 0.5,
    vitC: 190,
  },
  {
    id: "40",
    name: "Onion",
    serving: "~½ medium (70 g)",
    calories: 28,
    protein: 0.8,
    carbs: 6.4,
    fiber: 1.1,
    sugars: 4.2,
    fat: 0.1,
    sodium: 3,
    calcium: 14,
    iron: 0.1,
    vitC: 7,
  },
  {
    id: "41",
    name: "Garlic",
    serving: "1 clove (3 g)",
    calories: 4,
    protein: 0.2,
    carbs: 1.0,
    fiber: 0.1,
    sugars: 0.0,
    fat: 0.0,
    sodium: 0,
    calcium: 5,
    iron: 0.0,
    vitC: 1,
  },
  {
    id: "42",
    name: "Asparagus",
    serving: "5 spears (93 g)",
    calories: 20,
    protein: 2.2,
    carbs: 3.7,
    fiber: 2.1,
    sugars: 1.3,
    fat: 0.2,
    sodium: 14,
    calcium: 20,
    iron: 1.0,
    vitC: 12,
  },
  {
    id: "43",
    name: "Mushrooms",
    serving: "1 cup sliced (70 g)",
    calories: 15,
    protein: 2.2,
    carbs: 2.3,
    fiber: 1.0,
    sugars: 1.4,
    fat: 0.2,
    sodium: 4,
    calcium: 2,
    iron: 0.3,
    vitC: 2,
  },
  {
    id: "44",
    name: "Green beans",
    serving: "1 cup (110 g)",
    calories: 31,
    protein: 1.8,
    carbs: 7.0,
    fiber: 2.7,
    sugars: 3.3,
    fat: 0.1,
    sodium: 6,
    calcium: 37,
    iron: 0.7,
    vitC: 12,
  },
  {
    id: "45",
    name: "Cauliflower",
    serving: "1 cup (100 g)",
    calories: 25,
    protein: 1.9,
    carbs: 5.3,
    fiber: 2.0,
    sugars: 2.0,
    fat: 0.1,
    sodium: 30,
    calcium: 22,
    iron: 0.4,
    vitC: 48,
  },
  {
    id: "46",
    name: "Brussels sprouts",
    serving: "1 cup (88 g)",
    calories: 38,
    protein: 2.6,
    carbs: 8.0,
    fiber: 3.3,
    sugars: 2.2,
    fat: 0.3,
    sodium: 21,
    calcium: 34,
    iron: 1.2,
    vitC: 85,
  },
  {
    id: "47",
    name: "Cabbage",
    serving: "1 cup shredded (89 g)",
    calories: 22,
    protein: 1.1,
    carbs: 5.2,
    fiber: 2.2,
    sugars: 2.8,
    fat: 0.1,
    sodium: 18,
    calcium: 40,
    iron: 0.5,
    vitC: 36,
  },
  {
    id: "48",
    name: "Eggplant",
    serving: "1 cup cubed (99 g)",
    calories: 20,
    protein: 0.8,
    carbs: 4.8,
    fiber: 2.5,
    sugars: 2.9,
    fat: 0.1,
    sodium: 2,
    calcium: 9,
    iron: 0.2,
    vitC: 2,
  },
  {
    id: "49",
    name: "Zucchini",
    serving: "1 cup sliced (124 g)",
    calories: 21,
    protein: 1.5,
    carbs: 3.9,
    fiber: 1.9,
    sugars: 2.5,
    fat: 0.4,
    sodium: 8,
    calcium: 26,
    iron: 0.5,
    vitC: 20,
  },
  {
    id: "50",
    name: "Pumpkin",
    serving: "1 cup cubed (116 g)",
    calories: 30,
    protein: 1.1,
    carbs: 7.5,
    fiber: 2.7,
    sugars: 3.0,
    fat: 0.1,
    sodium: 1,
    calcium: 21,
    iron: 0.8,
    vitC: 9,
  },
  // --- Grains, Legumes, and Nuts ---
  {
    id: "51",
    name: "Rice, white cooked",
    serving: "1 cup (158 g)",
    calories: 205,
    protein: 3.8,
    carbs: 44,
    fiber: 0.6,
    sugars: 0,
    fat: 0.5,
    sodium: 2,
    calcium: 16,
    iron: 1.9,
    vitC: 0,
  },
  {
    id: "52",
    name: "Quinoa, cooked",
    serving: "1 cup (185 g)",
    calories: 222,
    protein: 8.1,
    carbs: 39.4,
    fiber: 5.2,
    sugars: 1.6,
    fat: 3.6,
    sodium: 13,
    calcium: 31,
    iron: 2.8,
    vitC: 0,
  },
  {
    id: "53",
    name: "Oatmeal (cooked)",
    serving: "1 cup (234 g)",
    calories: 159,
    protein: 5.6,
    carbs: 28,
    fiber: 4.0,
    sugars: 1.2,
    fat: 3.3,
    sodium: 115,
    calcium: 19,
    iron: 2.1,
    vitC: 0,
  },
  {
    id: "54",
    name: "Bread, white",
    serving: "1 slice (30 g)",
    calories: 80,
    protein: 2.3,
    carbs: 15.2,
    fiber: 0.7,
    sugars: 1.3,
    fat: 1.0,
    sodium: 204,
    calcium: 45,
    iron: 1.1,
    vitC: 0,
  },
  {
    id: "55",
    name: "Bread, whole wheat",
    serving: "1 slice (30 g)",
    calories: 74,
    protein: 3.9,
    carbs: 12.3,
    fiber: 2.1,
    sugars: 1.8,
    fat: 1.3,
    sodium: 180,
    calcium: 32,
    iron: 1.1,
    vitC: 0,
  },
  {
    id: "56",
    name: "Pasta, spaghetti",
    serving: "1 cup cooked (140 g)",
    calories: 221,
    protein: 8.1,
    carbs: 43.3,
    fiber: 2.5,
    sugars: 0.9,
    fat: 1.3,
    sodium: 2,
    calcium: 10,
    iron: 0.7,
    vitC: 0,
  },
  {
    id: "57",
    name: "Corn",
    serving: "1 medium ear (164 g)",
    calories: 177,
    protein: 5.4,
    carbs: 41.0,
    fiber: 4.6,
    sugars: 5.9,
    fat: 2.7,
    sodium: 15,
    calcium: 7,
    iron: 0.8,
    vitC: 11,
  },
  {
    id: "58",
    name: "Black beans, cooked",
    serving: "1 cup (172 g)",
    calories: 227,
    protein: 15.2,
    carbs: 40.8,
    fiber: 15.0,
    sugars: 0.3,
    fat: 0.9,
    sodium: 2,
    calcium: 46,
    iron: 3.6,
    vitC: 0,
  },
  {
    id: "59",
    name: "Chickpeas, cooked",
    serving: "1 cup (164 g)",
    calories: 269,
    protein: 14.5,
    carbs: 45.0,
    fiber: 12.5,
    sugars: 4.8,
    fat: 4.2,
    sodium: 11,
    calcium: 80,
    iron: 4.8,
    vitC: 2,
  },
  {
    id: "60",
    name: "Lentils, cooked",
    serving: "1 cup (198 g)",
    calories: 230,
    protein: 17.9,
    carbs: 39.9,
    fiber: 15.6,
    sugars: 2.0,
    fat: 0.8,
    sodium: 2,
    calcium: 38,
    iron: 6.6,
    vitC: 2,
  },
  {
    id: "61",
    name: "Almonds",
    serving: "1 oz (28 g)",
    calories: 162,
    protein: 6.0,
    carbs: 6.2,
    fiber: 3.5,
    sugars: 1.2,
    fat: 14,
    sodium: 1,
    calcium: 75,
    iron: 1.0,
    vitC: 0,
  },
  {
    id: "62",
    name: "Peanuts",
    serving: "1 oz (28 g)",
    calories: 161,
    protein: 7.3,
    carbs: 4.6,
    fiber: 2.4,
    sugars: 1.3,
    fat: 14,
    sodium: 1,
    calcium: 17,
    iron: 0.5,
    vitC: 0,
  },
  {
    id: "63",
    name: "Walnuts",
    serving: "1 oz (28 g)",
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fiber: 2.0,
    sugars: 0.7,
    fat: 18,
    sodium: 1,
    calcium: 27,
    iron: 0.8,
    vitC: 1,
  },
  {
    id: "64",
    name: "Chia seeds",
    serving: "1 oz (28 g)",
    calories: 138,
    protein: 4.7,
    carbs: 11.9,
    fiber: 9.8,
    sugars: 0.0,
    fat: 8.7,
    sodium: 5,
    calcium: 179,
    iron: 2.2,
    vitC: 0,
  },
  {
    id: "65",
    name: "Flax seeds",
    serving: "1 oz (28 g)",
    calories: 1
