
import type { Food } from "@/types";

export const MOCK_FOOD_DATABASE: Food[] = [
  {
    id: "1",
    name: "Apple",
    category: "Fruit",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    servingSize: "1 medium (182g)",
    quantity: 1,
    mealType: "snack",
    timestamp: "",
  },
  {
    id: "2",
    name: "Chicken Breast",
    category: "Protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    servingSize: "100g",
    quantity: 1,
    mealType: "lunch",
    timestamp: "",
  },
  {
    id: "3",
    name: "Brown Rice",
    category: "Grain",
    calories: 112,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    servingSize: "100g cooked",
    quantity: 1,
    mealType: "lunch",
    timestamp: "",
  },
  {
    id: "4",
    name: "Avocado",
    category: "Fruit",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    servingSize: "1/2 medium (100g)",
    quantity: 1,
    mealType: "breakfast",
    timestamp: "",
  },
  {
    id: "5",
    name: "Salmon",
    category: "Protein",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    servingSize: "100g",
    quantity: 1,
    mealType: "dinner",
    timestamp: "",
  },
  {
    id: "6",
    name: "Broccoli",
    category: "Vegetable",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    servingSize: "100g",
    quantity: 1,
    mealType: "dinner",
    timestamp: "",
  },
  {
    id: "7",
    name: "Greek Yogurt",
    category: "Dairy",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    servingSize: "100g",
    quantity: 1,
    mealType: "breakfast",
    timestamp: "",
  },
  {
    id: "8",
    name: "Almonds",
    category: "Nuts",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 49,
    servingSize: "100g",
    quantity: 1,
    mealType: "snack",
    timestamp: "",
  },
  {
    id: "9",
    name: "Banana",
    category: "Fruit",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    servingSize: "1 medium (118g)",
    quantity: 1,
    mealType: "snack",
    timestamp: "",
  },
  {
    id: "10",
    name: "Egg",
    category: "Protein",
    calories: 68,
    protein: 5.5,
    carbs: 0.6,
    fat: 4.8,
    servingSize: "1 large (50g)",
    quantity: 1,
    mealType: "breakfast",
    timestamp: "",
  },
];

export const CATEGORIES = [
  "All",
  "Fruit",
  "Vegetable",
  "Protein",
  "Grain",
  "Dairy",
  "Nuts",
];

export const initialRecent = ["apple", "chicken", "rice"];
