
export interface FoodFull {
  id: string;
  name: string;
  serving: string;
  calories: number;
  protein: number;
  carbs: number;
  fiber: number;
  sugars: number;
  fat: number;
  sodium: number;
  calcium: number;
  iron: number;
  vitC: number;
}

// A much more comprehensive food database with common foods from Western diets
export const FULL_FOOD_DATABASE: FoodFull[] = [
  {
    id: "1",
    name: "Apple (with skin)",
    serving: "1 medium (182g)",
    calories: 95,
    protein: 0.5,
    carbs: 25.1,
    fiber: 4.4,
    sugars: 18.9,
    fat: 0.3,
    sodium: 2,
    calcium: 11,
    iron: 0.2,
    vitC: 8.4,
  },
  {
    id: "2",
    name: "Banana",
    serving: "1 medium (118g)",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fiber: 3.1,
    sugars: 14.4,
    fat: 0.4,
    sodium: 1,
    calcium: 6,
    iron: 0.3,
    vitC: 10,
  },
  {
    id: "3",
    name: "Chicken breast (roasted)",
    serving: "½ breast (86g)",
    calories: 142,
    protein: 26.7,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 3.1,
    sodium: 64,
    calcium: 5,
    iron: 0.5,
    vitC: 0,
  },
  {
    id: "4",
    name: "Coffee, black",
    serving: "1 cup (240 ml)",
    calories: 2,
    protein: 0.3,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 5,
    calcium: 5,
    iron: 0,
    vitC: 0,
  },
  {
    id: "5",
    name: "Regular Beer",
    serving: "12 oz (355 ml)",
    calories: 153,
    protein: 1.7,
    carbs: 12.8,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 14,
    calcium: 14,
    iron: 0.01,
    vitC: 0,
  },
  {
    id: "6",
    name: "Water, plain",
    serving: "1 cup (240 ml)",
    calories: 0,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 0,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  {
    id: "7",
    name: "Tea, black",
    serving: "1 cup (240 ml)",
    calories: 2,
    protein: 0,
    carbs: 0.5,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 7,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  {
    id: "8",
    name: "Soda (Cola, reg.)",
    serving: "12 oz can (355 ml)",
    calories: 140,
    protein: 0,
    carbs: 39,
    fiber: 0,
    sugars: 39,
    fat: 0,
    sodium: 45,
    calcium: 2,
    iron: 0,
    vitC: 0,
  },
  {
    id: "9",
    name: "Diet Cola (no sugar)",
    serving: "12 oz can (355 ml)",
    calories: 1,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 40,
    calcium: 0,
    iron: 0,
    vitC: 0,
  },
  {
    id: "10",
    name: "Orange juice",
    serving: "8 oz glass (240 ml)",
    calories: 112,
    protein: 1.7,
    carbs: 26,
    fiber: 0.5,
    sugars: 21,
    fat: 0.3,
    sodium: 2,
    calcium: 20,
    iron: 0.5,
    vitC: 124,
  },
  {
    id: "11",
    name: "Milk, whole",
    serving: "1 cup (244 g)",
    calories: 149,
    protein: 7.9,
    carbs: 12,
    fiber: 0,
    sugars: 12,
    fat: 8.0,
    sodium: 105,
    calcium: 276,
    iron: 0,
    vitC: 0,
  },
  {
    id: "12",
    name: "Milk, low-fat (2%)",
    serving: "1 cup (244 g)",
    calories: 122,
    protein: 8.1,
    carbs: 12,
    fiber: 0,
    sugars: 12,
    fat: 4.8,
    sodium: 107,
    calcium: 293,
    iron: 0,
    vitC: 0,
  },
  {
    id: "13",
    name: "Light Beer",
    serving: "12 oz (355 ml)",
    calories: 104,
    protein: 0.9,
    carbs: 5.8,
    fiber: 0,
    sugars: 0,
    fat: 0,
    sodium: 10,
    calcium: 7,
    iron: 0,
    vitC: 0,
  },
  {
    id: "14",
    name: "Red Wine",
    serving: "5 oz (148 ml)",
    calories: 125,
    protein: 0.1,
    carbs: 4,
    fiber: 0,
    sugars: 0.9,
    fat: 0,
    sodium: 5,
    calcium: 12,
    iron: 0.5,
    vitC: 0,
  },
  {
    id: "15",
    name: "White Wine",
    serving: "5 oz (148 ml)",
    calories: 121,
    protein: 0.1,
    carbs: 3.8,
    fiber: 0,
    sugars: 1.4,
    fat: 0,
    sodium: 7,
    calcium: 9,
    iron: 0.3,
    vitC: 0,
  },
  {
    id: "16",
    name: "Orange",
    serving: "1 medium (154 g)",
    calories: 72,
    protein: 1.4,
    carbs: 18.1,
    fiber: 3.7,
    sugars: 14.5,
    fat: 0.2,
    sodium: 0,
    calcium: 62,
    iron: 0.1,
    vitC: 77,
  },
  {
    id: "17",
    name: "Grapes (seedless)",
    serving: "~20 grapes (92 g)",
    calories: 64,
    protein: 0.6,
    carbs: 16.6,
    fiber: 0.8,
    sugars: 14,
    fat: 0.2,
    sodium: 2,
    calcium: 10,
    iron: 0.2,
    vitC: 3,
  },
  {
    id: "18",
    name: "Strawberries",
    serving: "1 cup (152 g)",
    calories: 50,
    protein: 1.0,
    carbs: 11.7,
    fiber: 3.0,
    sugars: 7.4,
    fat: 0.5,
    sodium: 2,
    calcium: 24,
    iron: 0.4,
    vitC: 89,
  },
  {
    id: "19",
    name: "Tomato, raw",
    serving: "1 medium (123 g)",
    calories: 22,
    protein: 1.1,
    carbs: 4.8,
    fiber: 1.5,
    sugars: 3.2,
    fat: 0.3,
    sodium: 6,
    calcium: 12,
    iron: 0.4,
    vitC: 17,
  },
  {
    id: "20",
    name: "Potato, baked",
    serving: "1 med. w/ skin (173 g)",
    calories: 161,
    protein: 4.3,
    carbs: 36,
    fiber: 3.8,
    sugars: 2.2,
    fat: 0.2,
    sodium: 17,
    calcium: 17,
    iron: 1.2,
    vitC: 22,
  },
  {
    id: "21",
    name: "French fries",
    serving: "1 medium serv (117 g)",
    calories: 365,
    protein: 4.0,
    carbs: 48,
    fiber: 4.4,
    sugars: 0.4,
    fat: 17.6,
    sodium: 246,
    calcium: 21,
    iron: 0.9,
    vitC: 5.5,
  },
  {
    id: "22",
    name: "Bread, white",
    serving: "1 slice (30 g)",
    calories: 80,
    protein: 2.3,
    carbs: 15.2,
    fiber: 0.7,
    sugars: 1.3,
    fat: 1.0,
    sodium: 204,
    calcium: 45,
    iron: 1.1,
    vitC: 0,
  },
  {
    id: "23",
    name: "Bread, whole wheat",
    serving: "1 slice (30 g)",
    calories: 74,
    protein: 3.9,
    carbs: 12.3,
    fiber: 2.1,
    sugars: 1.8,
    fat: 1.3,
    sodium: 180,
    calcium: 32,
    iron: 1.1,
    vitC: 0,
  },
  {
    id: "24",
    name: "Ground beef (80% lean)",
    serving: "1 patty (113 g)",
    calories: 288,
    protein: 30,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 19.8,
    sodium: 85,
    calcium: 6,
    iron: 2.9,
    vitC: 0,
  },
  {
    id: "25",
    name: "Bacon (pork, pan-fried)",
    serving: "2 slices (16 g)",
    calories: 87,
    protein: 5.9,
    carbs: 0.2,
    fiber: 0,
    sugars: 0,
    fat: 6.7,
    sodium: 293,
    calcium: 2,
    iron: 0.1,
    vitC: 0,
  },
  {
    id: "26",
    name: "Egg, whole (boiled)",
    serving: "1 large (50 g)",
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fiber: 0,
    sugars: 0.6,
    fat: 5.3,
    sodium: 62,
    calcium: 25,
    iron: 0.6,
    vitC: 0,
  },
  {
    id: "27",
    name: "Salmon filet (baked)",
    serving: "1 fillet (154 g)",
    calories: 317,
    protein: 34,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 19,
    sodium: 88,
    calcium: 14,
    iron: 1.2,
    vitC: 0,
  },
  {
    id: "28",
    name: "Rice, white cooked",
    serving: "1 cup (158 g)",
    calories: 205,
    protein: 3.8,
    carbs: 44,
    fiber: 0.6,
    sugars: 0,
    fat: 0.5,
    sodium: 2,
    calcium: 16,
    iron: 1.9,
    vitC: 0,
  },
  {
    id: "29",
    name: "Pasta, spaghetti",
    serving: "1 cup cooked (140 g)",
    calories: 221,
    protein: 8.1,
    carbs: 43.3,
    fiber: 2.5,
    sugars: 0.9,
    fat: 1.3,
    sodium: 2,
    calcium: 10,
    iron: 0.7,
    vitC: 0,
  },
  {
    id: "30",
    name: "Cheddar cheese",
    serving: "1 slice (28 g)",
    calories: 113,
    protein: 7.0,
    carbs: 0.4,
    fiber: 0,
    sugars: 0.1,
    fat: 9.3,
    sodium: 174,
    calcium: 199,
    iron: 0.2,
    vitC: 0,
  },
  {
    id: "31",
    name: "Yogurt, plain",
    serving: "1 cup (245 g)",
    calories: 150,
    protein: 8.5,
    carbs: 11.5,
    fiber: 0,
    sugars: 11.5,
    fat: 8.0,
    sodium: 113,
    calcium: 296,
    iron: 0.1,
    vitC: 1,
  },
  {
    id: "32",
    name: "Almonds",
    serving: "1 oz (28 g)",
    calories: 162,
    protein: 6.0,
    carbs: 6.2,
    fiber: 3.5,
    sugars: 1.2,
    fat: 14,
    sodium: 1,
    calcium: 75,
    iron: 1.0,
    vitC: 0,
  },
  {
    id: "33",
    name: "Broccoli, cooked",
    serving: "~2 spears (150 g)",
    calories: 53,
    protein: 3.6,
    carbs: 10.8,
    fiber: 5.0,
    sugars: 2.1,
    fat: 0.6,
    sodium: 62,
    calcium: 60,
    iron: 1.1,
    vitC: 97,
  },
  {
    id: "34",
    name: "Olive oil",
    serving: "1 Tbsp (13.5 g)",
    calories: 119,
    protein: 0,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 13.5,
    sodium: 0,
    calcium: 1,
    iron: 0,
    vitC: 0,
  },
  {
    id: "35",
    name: "Potato chips",
    serving: "1 oz (28 g)",
    calories: 150,
    protein: 2.0,
    carbs: 15,
    fiber: 1.3,
    sugars: 0.1,
    fat: 9.5,
    sodium: 147,
    calcium: 7,
    iron: 0.4,
    vitC: 9,
  },
  {
    id: "36",
    name: "Chocolate bar (milk)",
    serving: "1 bar (44 g)",
    calories: 235,
    protein: 3.4,
    carbs: 26,
    fiber: 1.5,
    sugars: 22.9,
    fat: 13.2,
    sodium: 35,
    calcium: 83,
    iron: 1.1,
    vitC: 0,
  },
  {
    id: "37",
    name: "McDonald's Big Mac",
    serving: "1 burger (219 g)",
    calories: 563,
    protein: 25.9,
    carbs: 44,
    fiber: 3.5,
    sugars: 8.7,
    fat: 32.8,
    sodium: 1007,
    calcium: 254,
    iron: 4.4,
    vitC: 0.9,
  },
  {
    id: "38",
    name: "Spinach, raw",
    serving: "1 cup (30 g)",
    calories: 7,
    protein: 0.9,
    carbs: 1.1,
    fiber: 0.7,
    sugars: 0.1,
    fat: 0.1,
    sodium: 24,
    calcium: 30,
    iron: 0.8,
    vitC: 8,
  },
  {
    id: "39",
    name: "Peanut butter",
    serving: "2 Tbsp (32 g)",
    calories: 188,
    protein: 8.0,
    carbs: 6.4,
    fiber: 1.9,
    sugars: 3.2,
    fat: 16,
    sodium: 5,
    calcium: 14,
    iron: 0.5,
    vitC: 0,
  },
  {
    id: "40",
    name: "Honey",
    serving: "1 Tbsp (21 g)",
    calories: 64,
    protein: 0,
    carbs: 17,
    fiber: 0,
    sugars: 17,
    fat: 0,
    sodium: 1,
    calcium: 2,
    iron: 0,
    vitC: 0,
  },
  {
    id: "41",
    name: "Avocado",
    serving: "1 medium (150 g)",
    calories: 240,
    protein: 3.0,
    carbs: 12.0,
    fiber: 10.0,
    sugars: 0.7,
    fat: 22.0,
    sodium: 10,
    calcium: 18,
    iron: 1.0,
    vitC: 12,
  },
  {
    id: "42",
    name: "Mango",
    serving: "~½ fruit (100 g)",
    calories: 60,
    protein: 0.8,
    carbs: 15.0,
    fiber: 1.6,
    sugars: 13.7,
    fat: 0.2,
    sodium: 1,
    calcium: 7,
    iron: 0.1,
    vitC: 36,
  },
  {
    id: "43",
    name: "Oatmeal (cooked)",
    serving: "1 cup (234 g)",
    calories: 159,
    protein: 5.6,
    carbs: 28,
    fiber: 4.0,
    sugars: 1.2,
    fat: 3.3,
    sodium: 115,
    calcium: 19,
    iron: 2.1,
    vitC: 0,
  },
  {
    id: "44",
    name: "Granola bar",
    serving: "1 bar (24 g)",
    calories: 103,
    protein: 1.7,
    carbs: 17.3,
    fiber: 0.9,
    sugars: 7.4,
    fat: 3.4,
    sodium: 72,
    calcium: 20,
    iron: 0.3,
    vitC: 0,
  },
  {
    id: "45",
    name: "Ice cream, vanilla",
    serving: "½ cup (66 g)",
    calories: 137,
    protein: 2.3,
    carbs: 15.2,
    fiber: 0,
    sugars: 13.9,
    fat: 7.3,
    sodium: 53,
    calcium: 85,
    iron: 0.1,
    vitC: 0,
  },
  {
    id: "46",
    name: "Pizza (pepperoni)",
    serving: "1 large slice (107 g)",
    calories: 317,
    protein: 12.9,
    carbs: 35.3,
    fiber: 2.0,
    sugars: 3.8,
    fat: 12.8,
    sodium: 684,
    calcium: 201,
    iron: 2.7,
    vitC: 1.2,
  },
  {
    id: "47",
    name: "Tofu, firm",
    serving: "~½ cup (100 g)",
    calories: 76,
    protein: 8.1,
    carbs: 1.9,
    fiber: 0.3,
    sugars: 0.7,
    fat: 4.8,
    sodium: 7,
    calcium: 350,
    iron: 5.4,
    vitC: 0,
  },
  {
    id: "48",
    name: "Sweet potato, baked",
    serving: "1 medium (114 g)",
    calories: 103,
    protein: 2.3,
    carbs: 24,
    fiber: 3.8,
    sugars: 7.4,
    fat: 0.2,
    sodium: 27,
    calcium: 18,
    iron: 0.5,
    vitC: 2,
  },
  {
    id: "49",
    name: "Butter (salted)",
    serving: "1 tbsp (14 g)",
    calories: 100,
    protein: 0.1,
    carbs: 0,
    fiber: 0,
    sugars: 0,
    fat: 11.4,
    sodium: 90,
    calcium: 3,
    iron: 0,
    vitC: 0,
  },
  {
    id: "50",
    name: "Lettuce (iceberg)",
    serving: "1 cup shredded (72 g)",
    calories: 10,
    protein: 0.6,
    carbs: 2.2,
    fiber: 0.9,
    sugars: 1.3,
    fat: 0.1,
    sodium: 7,
    calcium: 13,
    iron: 0.3,
    vitC: 2,
  }
];

