import type { Food, FoodCategory } from "@/types";

export const MOCK_FOOD_DATABASE: Food[] = [
  {
    id: "1",
    name: "Apple",
    category: "fruit",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugars: 10.0,
    sodium: 1,
    calcium: 6,
    iron: 0.1,
    vitaminC: 4.6,
    serving: "1 medium (182g)",
    servingSize: "1 medium (182g)",
    quantity: 1,
    mealType: "snack",
    timestamp: "",
  },
  {
    id: "2",
    name: "Chicken Breast",
    category: "protein",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugars: 0,
    sodium: 74,
    calcium: 6,
    iron: 0.9,
    vitaminC: 0,
    serving: "100g",
    servingSize: "100g",
    quantity: 1,
    mealType: "lunch",
    timestamp: "",
  },
  {
    id: "3",
    name: "Brown Rice",
    category: "grain",
    calories: 112,
    protein: 2.6,
    carbs: 23.5,
    fat: 0.9,
    fiber: 1.6,
    sugars: 0,
    sodium: 5,
    calcium: 10,
    iron: 0.4,
    vitaminC: 0,
    serving: "100g cooked",
    servingSize: "100g cooked",
    quantity: 1,
    mealType: "lunch",
    timestamp: "",
  },
  {
    id: "4",
    name: "Avocado",
    category: "fruit",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugars: 0.7,
    sodium: 7,
    calcium: 12,
    iron: 0.6,
    vitaminC: 10,
    serving: "1/2 medium (100g)",
    servingSize: "1/2 medium (100g)",
    quantity: 1,
    mealType: "breakfast",
    timestamp: "",
  },
  {
    id: "5",
    name: "Salmon",
    category: "protein",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    sugars: 0,
    sodium: 57,
    calcium: 9,
    iron: 0.8,
    vitaminC: 0,
    serving: "100g",
    servingSize: "100g",
    quantity: 1,
    mealType: "dinner",
    timestamp: "",
  },
  {
    id: "6",
    name: "Broccoli",
    category: "vegetable",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 3.3,
    sugars: 1.4,
    sodium: 41,
    calcium: 40,
    iron: 0.7,
    vitaminC: 65,
    serving: "100g",
    servingSize: "100g",
    quantity: 1,
    mealType: "dinner",
    timestamp: "",
  },
  {
    id: "7",
    name: "Greek Yogurt",
    category: "dairy",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sugars: 3.6,
    sodium: 46,
    calcium: 121,
    iron: 0.1,
    vitaminC: 0,
    serving: "100g",
    servingSize: "100g",
    quantity: 1,
    mealType: "breakfast",
    timestamp: "",
  },
  {
    id: "8",
    name: "Almonds",
    category: "nut",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 49,
    fiber: 12.5,
    sugars: 4.4,
    sodium: 1,
    calcium: 269,
    iron: 3.7,
    vitaminC: 0,
    serving: "100g",
    servingSize: "100g",
    quantity: 1,
    mealType: "snack",
    timestamp: "",
  },
  {
    id: "9",
    name: "Banana",
    category: "fruit",
    calories: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    sugars: 12.2,
    sodium: 1,
    calcium: 5,
    iron: 0.3,
    vitaminC: 8.7,
    serving: "1 medium (118g)",
    servingSize: "1 medium (118g)",
    quantity: 1,
    mealType: "snack",
    timestamp: "",
  },
  {
    id: "10",
    name: "Egg",
    category: "protein",
    calories: 68,
    protein: 5.5,
    carbs: 0.6,
    fat: 4.8,
    fiber: 0,
    sugars: 0.6,
    sodium: 124,
    calcium: 50,
    iron: 1.2,
    vitaminC: 0,
    serving: "1 large (50g)",
    servingSize: "1 large (50g)",
    quantity: 1,
    mealType: "breakfast",
    timestamp: "",
  },
];

export const CATEGORIES: FoodCategory[] = [
  "beverage",
  "alcohol",
  "fruit",
  "vegetable",
  "grain",
  "legume",
  "nut",
  "dairy",
  "protein",
  "condiment",
  "fat",
  "oil",
  "snack",
  "sweet",
  "mixed",
  "other",
];
